### ISSUE TITLE
packet data contains header

### ISSUE THREAD

**Issue by Spookhub** [courvoif/pcap-file#11]
as title, the data array has the header with in it, was this deliberate?

**Comment by Spookhub** [comment]
in packet.rs
line 160
        let len = header.incl_len as usize;
        Ok(
            Packet {

                header : header,
                data : Cow::Borrowed(&slice[42..len]) /*not 0 should be 42 or which hex udp header standard you use?*/
            }
        )

**Comment by courvoif** [comment]
I'm pretty sure it doesn't, can you provide an example/show me the portion of the code that misbehaves ?

**Comment by Spookhub** [comment]
sure, see this screenshot
https://imgur.com/a/8xSWsGM
right hand side is wireshark, left hand side is studio code (printing a .pcap packet with pcap_file). Both have the same .pcap data open. wireshark has the header and data separated.
left hand side has the header and then the data cow has the packet data and the header.

**Comment by Spookhub** [comment]
```
    pub fn from_slice<B: ByteOrder>(slice: &[u8]) -> ResultChain<Packet> {
   //*snip*
      
        Ok(
            Packet {

                header : header,
                data : Cow::Borrowed(&slice[0 /*should be header.length?*/ ..len])
            }
        )
    }
```

**Comment by courvoif** [comment]
Hi, what you're showing me are the data of the UDP protocol. The data field of the Packet struct is the data of all the packet, starting from the first protocol layer (Ethernet in your case).

**Comment by Spookhub** [comment]
I see, Thank you for clarifying!
