### ISSUE TITLE
1.0.1 not working?

### ISSUE THREAD

**Issue by shirshak55** [courvoif/pcap-file#13]
It prints this:
```
➜  rust-parser cargo run
    Blocking waiting for file lock on package cache
    Updating crates.io index
error: failed to select a version for the requirement `pcap-file = "^1.0.1"`
  candidate versions found which didn't match: 0.10.0, 0.9.0, 0.8.0, ...
  location searched: crates.io index
required by package `rust-parser v0.1.0 (/Users/quantum/Desktop/code/rust-parser)`
```

**Comment by shirshak55** [comment]
1.0.1 is yanked meaning should we use 0.10.0?

**Comment by courvoif** [comment]
Yes, sorry for the inconvenience. There is an unsound use of unsafe in V1.01, I will update it as soon as possible.

**Comment by shirshak55** [comment]
@courvoif no problem and we are consumer so you don't need to say sorry. I was just reading the source code and I really liked how u use Cow implementation.

**Comment by shirshak55** [comment]
I am closing as u have already said in readme regarding soundness issue.
