### ISSUE TITLE
live capture

### ISSUE THREAD

**Issue by mikewalshchicago** [courvoif/pcap-file#15]
Is it possible to use this crate to record packets received from a live capture from pcap or another library?

**Comment by courvoif** [comment]
Yes, once you received the packets (with the libpcap for example) you can use my crate to write them to  a File or you preferred Writer. 

`let file_out = File::create("out.pcap").expect("Error creating file out");
let mut pcap_writer = PcapWriter::new(file_out).expect("Error writing file");

// Read the packet from you prefered input
for packet in packer_reader {

    //Write each packet of test.pcap in out.pcap
    pcap_writer.write(timestamp_sec, timestamp_ns, packet, packet.len()).unwrap();
}`
