### ISSUE TITLE
Flushing packets

### ISSUE THREAD

**Issue by gdetrez** [courvoif/pcap-file#16]
Hello! Thanks for making this crate available! I've been using it to build a small tool that reads packets out of some custom hardware at work and write them to pcap files.

When I write the packets to stdout and pipe it to another tool for analysis, I noticed that the packets arrive in batches.  I  believe this is because `Stdout` in the rust std library is buffered by default (it is [wrapped in a `LineWriter`](https://github.com/rust-lang/rust/blob/46ec74e60f238f694b46c976d6217e7cf8d4cf1a/src/libstd/io/stdio.rs#L418)).

As a workaround, I'm wrapping `Stdout`, again, in a writer that calls `flush` on every call to `write`. But this feels a bit dirty and is probably not very efficient as `PCAPWriter` does multiple `write` calls per packets and I only care about flushing after the complete packet data has been written.

So I'm wondering if you think it would make sense for `PCAPWriter` to offer the possibility to flush the writer after each packet?

**Comment by courvoif** [comment]
Hello,

I think that kind of possibility should be implemented on the wrapped Writer just like you did.
For me it's not the "purpose" of PcapWriter to choose to flush or not after a write.

You could do it like that too:
````rust
let stdout = std::io::stdout();
let mut pcap_writer = PcapWriter::new(stdout.lock()).unwrap();
let data = [0_u8; 64];

pcap_writer.writer(0, 0, data, 64).unwrap();
pcap_writer.get_mut().flush().unwrap();

**Comment by gdetrez** [comment]
Oh, that's a nice solution, thanks!  I didn't realize I could easily access the underlying writer.  I think you're right about this being out of scope for PcapWriter.  Thanks again for making this crate.
