### ISSUE TITLE
'attempt to multiply with overflow' in Header constuctor

### ISSUE THREAD

**Issue by barrygreengus** [courvoif/pcap-file#20]
The packet header constructor uses this line to convert nanoseconds to microseconds
`let mut ts_msec = ts_nsec * 1000;`

u32::MAX is 4,294,967,295, so when ts_nsec is at least 4,294,968, the constructor panics with  `'attempt to multiply with overflow' pcap-file-1.1.1/src/pcap/packet.rs:51:13`

There are 1 billion nanoseconds in one second, so a ts_nsec value of up to 999,999,999 should be valid.

Changing that line to: `let mut ts_msec = ts_nsec as u64 * 1000;` should fix it. Working on a PR

**Comment by barrygreengus** [comment]
It seems I just don't have the latest version, but the latest version still doesn't allow valid nanoseconds
```
 48             ts_nsec = ts_nsec.checked_mul(1000).ok_or(PcapError::InvalidField("Packet Header ts_microsecond can't be converted to nanosecond"))?;
```
It should still use u64 for nsec

**Comment by courvoif** [comment]
I'm currently re-writing the whole crate to have better ergonomics and performances.

Nervertheless in the current master branch, the following assumptions should be true for a packet:
- captured_len <= origin_len
- fractional part of the ts is always <= 10^6 or 10^9 depending of the timestamp resolution
