### ISSUE TITLE
Add CI on LE/BE and 32/64-bit targets

### ISSUE THREAD

**Issue by sekineh** [courvoif/pcap-file#3]
Because pcap is endian dependent, it's safer to continuously test on both LE and BE platform.

**Comment by courvoif** [comment]
It's right but this lib should be agnostic over the endianness of the platform.
It automatically detects the endianess of the pcap file for reading, and for writing you can specify it with BE being the default choice.
I will add test for LE/BE to verify that the read/write are correct though.

Unless I missed something I don't see what the pointer size of the platform can change for this lib.
What are your concerns about this ?

**Comment by courvoif** [comment]
@sekineh ?

**Comment by sekineh** [comment]
Thanks for the clear explanation. No more concrete concern. I appreciate your clear work.

By the way, writing in LE by default may be more performant when it is consumed by Intel machines.  But I can specify endianness explicitly, I don’t see big problem!
