### ISSUE TITLE
PacketHeader timestamps as std::time::Duration

### ISSUE THREAD

**Issue by Camotubi** [courvoif/pcap-file#7]
Hi again,
I know that this library maps directly to the wireshark spec of the pcap file format. The issue is that the tv_usec variable in the PacketHeader struct is a bit misleading. I'm aware that in the docs its says nanosecond/microsecond part of the timestamp, but the variable name is called tv_usec. This also requires the user of the library to know about the magic numbers on pcap files and what they mean. This tv_usec is kind of opened to interpretation. I was lucky that all the pcaps that I was using where microsecond files. 

I'm propousing either a method on PacketHeader to convert the timestamp to a std::time::Duration (taking into account the magic number) or rewriting the struct itself to store a std::time::Duration.

**Comment by courvoif** [comment]
Hi,
You're right PacketHeader definitely needs a method that returns a Duration with the right timestamp.
I don't really know if I should stick to the format and have a 1:1 mapping between the struct fields and the field of the format.Or if I should make an abstraction over all the format.

**Comment by courvoif** [comment]
So I added a function to a packet header to get the timestamp as a Duraiton.
I changed the field ts_usec to ts_nsec to only store the timestamp in nanosecond (the conversion is done automatically by the the PcapReader).

**Comment by Camotubi** [comment]
Good Job dude.
